In [ ]:
import pandas as pd
from datetime import timedelta
from datetime import datetime

# Declare variable here
startTime = datetime(2022,11,1,11,59,2)+ timedelta(hours=8)
gen_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
df_list = ['cp01','cp02','cp03','cp04','cp05','cp06','cp07','cp08','cp09','cp10','cp11','cp12','cp14','cp14','cp15','cp16']
question = "題目Question"
question01 = "銅鐘最後一次敲鐘是第幾年？"
question02 = "你是否已經完成任務？"
question03 = "香港女童軍新總部大樓地盤圍牆總共有多少幅壁畫？"
question04 = "你是否已經完成任務？"
question05 = "油麻地果欄是香港幾級歷史建築？"
question06 = "文物探知館前身是威菲路軍營S61及 S62座，兩座營房始建於哪一個年代？"
question07 = "K11 Art Mall中的四大區域的名稱是甚麼？"
question08 = "清真寺能穿鞋進入"
question09 = "你是否已經完成任務？"

In [32]:
#E001 前九廣鐵路鐘樓
cp01 = pd.read_csv('./exp_record/exp_01.csv')
cp01.rename(columns={question01:question},inplace=True)
cp01['CP01']=0
cp01.loc[cp01.question01 == 'correct', 'CP01'] = 50
cp01.loc[cp01.question01 != 'correct', 'CP01'] = 0
cp01.drop(labels=["ObjectID","CreationDate","GlobalID","Editor", "x","y", question, "EditDate"], axis=1, inplace=True)

#E002 戲曲中心
cp02 = pd.read_csv('./exp_record/exp_02.csv')
cp02.rename(columns={question02:question},inplace=True)
cp02['CP02(Visit)']=True
cp01['CP02']=0
cp02.loc[cp02.question == correct, 'CP02'] = 50
cp02.loc[cp02.question != correct, 'CP02'] = 0
cp02.drop(labels=["ObjectID","CreationDate","EditDate","GlobalID","Editor", "x","y", question], axis=1, inplace=True)

#E003 香港女童軍新總部大樓地盤
cp03 = pd.read_csv('./exp_record/exp_03.csv')
cp03.rename(columns={question03:question},inplace=True)
cp03['CP03']=0
cp03.loc[cp03.question == correct, 'CP03'] = 50
cp03.loc[cp03.question != correct, 'CP03'] = 0
cp03.drop(labels=["ObjectID","CreationDate","EditDate","GlobalID","Editor", "x","y", question], axis=1, inplace=True)

#E004 星光大道
cp04 = pd.read_csv('./exp_record/exp_04.csv')
cp04.rename(columns={question04:question},inplace=True)
cp02['CP04(Visit)']=True
cp04['CP04']=0
cp04.loc[cp04.question == correct, 'CP04'] = 50
cp04.loc[cp04.question != correct, 'CP04'] = 0
cp04.drop(labels=["ObjectID","CreationDate","EditDate","GlobalID","Editor", "x","y", question], axis=1, inplace=True)

#E005 聖安德烈堂
cp05 = pd.read_csv('./exp_record/exp_05.csv')
cp05.rename(columns={question05:question},inplace=True)
cp05['CP05']=0
cp05.loc[cp05.question == correct, 'CP05'] = 10
cp05.loc[cp05.question != correct, 'CP05'] = 0
cp05.drop(labels=["ObjectID","CreationDate","EditDate","GlobalID","Editor", "x","y", question], axis=1, inplace=True)

#E006 文物探知館
cp06 = pd.read_csv('./exp_record/exp_06.csv')
cp06.rename(columns={question06:question},inplace=True)
cp06['CP06']=0
cp06.loc[cp06.question == correct, 'CP06'] = 10
cp06.loc[cp06.question != correct, 'CP06'] = 0
cp06.drop(labels=["ObjectID","CreationDate","EditDate","GlobalID","Editor", "x","y", question], axis=1, inplace=True)

#E007 K11 Art Mall 
cp07 = pd.read_csv('./exp_record/exp_07.csv')
cp07.rename(columns={question07:question},inplace=True)
cp07['CP07']=0
cp07.loc[cp07.question == correct, 'cp07(Score)'] = 10
cp07.loc[cp07.question != correct, 'cp07(Score)'] = 0
cp07.drop(["ObjectID", "CreationDate","GlobalID","EditDate","Editor", "x","y", question], axis=1, inplace=True)

#E008 九龍清真寺
cp08 = pd.read_csv('./exp_record/exp_08.csv')
cp08.rename(columns={question08:question},inplace=True)
cp08['CP08']=0
cp08.loc[cp08.question == correct, 'CP08'] = 10
cp08.loc[cp08.question != correct, 'CP08'] = 0
cp08.drop(labels=["ObjectID","CreationDate","EditDate","GlobalID","Editor", "x","y", question], axis=1, inplace=True)

#E009 香港女童軍總會
cp09 = pd.read_csv('./exp_record/exp_09.csv')
cp09.rename(columns={question09:question},inplace=True)
cp09.rename(columns={"EditDate":"FinishTime"},inplace=True)

cp09.drop(labels=["ObjectID","CreationDate","GlobalID","Editor", "x","y",question], axis=1, inplace=True)

In [41]:
master = df_list[0]
for df in df_list[1:]:
    master = pd.merge(master, df, on='Creator', how="outer")
master['Total Time']=''
master['IsComplete']=False
master['IsBooth']= False
master['IsCheckPoint']= False
master['Total Score']=0
master['Achievement (Y/N)']=False

pd.options.display.float_format = '{:,.0f}'.format

master.rename(columns={"Creator":"Team Name"},inplace=True)
master.loc[master.FinishTime.notnull(), "IsComplete"]=True
master.loc[(master['CP02(Visit)']==True) | (master['CP04(Visit)']==True), 'IsBooth'] = True
###Sumation for length of passing
master.loc[master.IsComplete == True, 'Total Score']= master[["CP01","CP02","CP03","CP04","CP05","CP06","CP07","CP08"]].sum(1)
master.loc[master['Total Score'] >= 20, "IsCheckPoint"]=True
master.loc[(master['IsBooth'] == True) & (master['IsCheckPoint'] == True), "Achievement (Y/N)"]=True

master.FinishTime = pd.to_datetime(master.FinishTime)
master['FinishTime'] = master['FinishTime']+ timedelta(hours=8)
master.loc[master.IsComplete == True,'Total Time']=master["FinishTime"]-startTime
master['Total Time'] = master['Total Time'].astype(str).str.replace('0 days ', '')
master['Seconds'] = ''
master['Seconds'] = master['Total Time'] / pd.Timedelta(seconds=1)
master.sort_values(by=['Achievement (Y/N)','Total Score', 'Total Time', 'Team Name'], ascending=[False, False, True, True], inplace=True)
master= master[order]

########Format Table####################################
master = master.reset_index(drop=True)
master.index += 1
master.columns.name = 'Position'
master.drop(labels=['Seconds'], axis=1, inplace=True)
master = master.fillna('abs')
master['Achievement (Y/N)'] = master['Achievement (Y/N)'].map({True: 'Y', False: 'N'})
master['CP02'] = master['CP02'].map({True: 'Y', False: 'N'})
master['CP04'] = master['CP04'].map({True: 'Y', False: 'N'})
master['IsBooth'] = master['IsBooth'].map({True: 'Y', False: 'N'})
master['IsCheckPoint'] = master['IsCheckPoint'].map({True: 'Y', False: 'N'})

public_list = master.copy()
public_list.drop(labels=['FinishTime', 'CP01','CP02(Visit)','CP02','CP03','CP04(Visit)','CP04','CP05','CP06','CP07','CP08', 'IsBooth', 'IsCheckPoint', 'IsComplete'], axis=1, inplace=True)

master.sort_values(by=['Team Name'], ascending=[True], inplace=True)
master.to_csv('master_experience.csv',sep=',', header=True, index=False)

Position,Team Name,CP01,CP02,CP03,CP04,CP05,CP06,CP07,CP08,FinishTime,IsComplete,Total Time,Total Score,IsBooth,IsCheckPoint,Achievement (Y/N)
8,hkggatut01,10,N,0,N,0,10,0,10,2022-11-01 20:56:00,True,00:56:58,30,N,Y,N
17,hkggatut02,10,N,0,N,0,0,0,10,2022-11-01 20:57:00,True,00:57:58,20,N,Y,N
18,hkggatut03,0,N,0,N,0,10,0,10,2022-11-01 20:58:00,True,00:58:58,20,N,Y,N
30,hkggatut04,0,N,0,N,10,0,0,0,2022-11-01 20:59:00,True,00:59:58,10,N,N,N
1,hkggatut05,10,N,0,Y,0,10,0,0,2022-11-01 21:00:00,True,01:00:58,20,Y,Y,Y
31,hkggatut06,10,N,0,N,0,0,0,0,2022-11-01 21:01:00,True,01:01:58,10,N,N,N
9,hkggatut07,0,N,0,N,10,10,0,10,2022-11-01 21:03:00,True,01:03:58,30,N,Y,N
79,hkggatut08,0,N,0,N,0,0,0,0,2022-11-01 21:04:00,True,01:04:58,0,N,N,N
19,hkggatut09,10,N,0,N,0,10,0,0,2022-11-01 21:05:00,True,01:05:58,20,N,Y,N
10,hkggatut10,10,N,0,N,10,0,0,10,2022-11-01 21:06:00,True,01:06:58,30,N,Y,N
2,hkggatut11,0,N,0,Y,0,10,0,10,2022-11-01 21:07:00,True,01:07:58,20,Y,Y,Y
80,hkggatut12,0,N,0,N,0,0,0,0,2022-11-01 21:09:00,True,01:09:58,0,N,N,N
11,hkggatut13,10,N,0,N,10,10,0,0,2022-11-01 21:10:00,True,01:10:58,30,N,Y,N
20,hkggatut14,10,N,0,N,0,0,0,10,2022-11-01 21:11:00,True,01:11:58,20,N,Y,N
21,hkggatut15,0,N,0,N,0,10,0,10,2022-11-01 21:12:00,True,01:12:58,20,N,Y,N
81,hkggatut16,0,N,0,N,0,0,0,0,2022-11-01 21:13:00,True,01:13:58,0,N,N,N
12,hkggatut17,10,N,0,N,10,10,0,0,2022-11-01 21:14:00,True,01:14:58,30,N,Y,N
22,hkggatut18,10,N,0,N,0,0,0,10,2022-11-01 21:16:00,True,01:16:58,20,N,Y,N
13,hkggatut19,0,N,0,N,10,10,0,10,2022-11-01 21:17:00,True,01:17:58,30,N,Y,N
82,hkggatut20,0,N,0,N,0,0,0,0,2022-11-01 21:18:00,True,01:18:58,0,N,N,N

In [55]:
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("experience_template.html", column_names=public_list.columns.values, row_data=list(public_list.values.tolist()), zip=zip, date=gen_time)

app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Nov/2022 15:29:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Nov/2022 15:29:37] "GET /static/img/logo.png HTTP/1.1" 304 -